"""
RAGAS metrics integration for LLM-as-a-Judge chain.

Uses RAGAS library to compute Response Relevancy scores via:
  - LLM: LiteLLM Proxy (judge model) for question reverse-generation
  - Embeddings: Local HuggingFace model for cosine similarity

Metric names follow the common metrics standard (langchain-design.md §1.1).
"""
import logging
from functools import lru_cache

from openai import OpenAI
from ragas.llms import llm_factory
from ragas.embeddings import HuggingFaceEmbeddings
from ragas.metrics.collections import AnswerRelevancy

from settings import settings

logger = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def _get_ragas_llm():
    """Create RAGAS-compatible LLM via LiteLLM Proxy. Cached singleton."""
    # Strip /v1 suffix — RAGAS llm_factory with adapter="litellm"
    # expects the base URL without the path.
    base_url = settings.litellm_proxy_url
    if base_url.endswith("/v1"):
        base_url = base_url[:-3]

    client = OpenAI(
        api_key=settings.litellm_api_key,
        base_url=base_url,
    )
    model_config = settings.models.get("judge", {})
    model_name = model_config.get("litellm_model_name", "judge")
    return llm_factory(model_name, client=client, adapter="litellm")


@lru_cache(maxsize=1)
def _get_ragas_embeddings():
    """Create local HuggingFace embeddings. Cached singleton."""
    return HuggingFaceEmbeddings(model=settings.ragas_embedding_model)


@lru_cache(maxsize=1)
def _get_response_relevancy_scorer() -> AnswerRelevancy:
    """Create Response Relevancy scorer. Cached singleton."""
    return AnswerRelevancy(
        llm=_get_ragas_llm(),
        embeddings=_get_ragas_embeddings(),
    )


async def compute_response_relevancy(
    user_input: str,
    response: str,
) -> float:
    """
    Compute RAGAS Response Relevancy score.

    Algorithm: Reverse-generate N artificial questions from the response,
    then compute mean cosine similarity between each generated question
    and the original user_input.

    Args:
        user_input: The original question from the user.
        response: The answer generated by the Reasoner LLM.

    Returns:
        Score between 0.0 and 1.0 (higher = more relevant).
        Returns 0.0 on error to trigger retry.
    """
    try:
        scorer = _get_response_relevancy_scorer()
        result = await scorer.ascore(
            user_input=user_input,
            response=response,
        )
        score = float(result.value)
        logger.info(
            "Response Relevancy score: %.3f (input=%r)",
            score,
            user_input[:80],
        )
        return score
    except Exception:
        logger.exception("Failed to compute Response Relevancy")
        # Return 0.0 on error so the chain treats it as FAIL and retries
        return 0.0
